apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: audit-and-block
  namespace: multiubuntu
spec:
  file:
    matchDirectories:
    - action: Audit
      dir: /usr/bin/
      message: Auditing /bin/ directory
      readOnly: true
      recursive: true
      severity: 3
    - action: Block
      dir: /sbin/
      message: Blocking write action in /sbin/ directory
      readOnly: true
      recursive: true
      severity: 3
  network:
    matchProtocols:
    - action: Audit
      fromSource:
      - path: /bin/ping
      message: Auditing Ping Network Operation
      protocol: icmp
      severity: 1
    - action: Block
      fromSource:
      - path: /usr/bin/curl
      message: Blocking curl network operation
      protocol: tcp
      severity: 1
  process:
    matchPaths:
    - action: Audit
      message: Auditing /bin/ls execution
      path: /bin/ls
      severity: 8
    - action: Block
      message: Blocking /bin/hostname execution
      path: /bin/hostname
      severity: 5
  selector:
    matchLabels:
      container: ubuntu-1
  tags:
    - CIS
    - FIGHT
    - MITRE
    - NIST
    - PCI_DSS
